name: integration tests (INTR)

on:
    push:
        branches:
            - master
            - brendon/parachain-v1-17-0-pre-foreign-asset

concurrency:
    group: ${{ github.ref }}_intr
    cancel-in-progress: true

jobs:
    test_intr:
        uses: ./.github/workflows/reusable-wf-integration-tests.yml
        with:
            parachain: INTR
